[package]
name = "model-demo"
version = "0.1.0"
authors = ["Oliver Scherer <github35764891676564198441@oli-obk.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.14.4"
quote = "0.6.3"
